### PR TITLE
Improve getting "wefField" in "UpdateWorkItemBoardColumn" Method 

### PR DESCRIPTION
**Pull request by shayki5**
There is "to do" for this mission. 
Instead of "forach" over all the fields I using Linq to get the wefField name.

### CODE REVIEW

**Comment by shayki5** [comment]
I see the build failed so I close this PR.

**Comment by shayki5** [comment]
I saw the build failed so I added System.Linq reference.

**Comment by vtbassmatt** [comment]
I'm sorry for the long delay in responding. If you'll retarget this PR at `main` I'll be happy to merge it.

**Comment by shayki5** [comment]
@vtbassmatt Done - https://github.com/microsoft/azure-devops-dotnet-samples/pull/289
Thank you!

**Comment by vtbassmatt** [comment]
Replaced by another PR, so closing this one. Thanks!

**Comment by shayki5** [comment]
Thanks Matt!

**Pull request closed without merging**
